name: Debug Build and Test

on: [push, pull_request]

jobs:
  build-debug:
    runs-on: windows-2022

    steps:
      # Checkout the repository code
      - name: Checkout and Initialise
        uses: actions/checkout@v4

      # Install the required .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      # Cache the nuget packages
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/ZDs.csproj') }}

      # Restore, build, and test
      - name: Restore dependencies
        run: dotnet restore

      - name: Build Debug
        run: dotnet build --no-restore --configuration Debug

      - name: Test Debug
        run: dotnet test --no-build --configuration Debug

      # Upload the build artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZDs-debug-${{ github.sha }}
          path: |
            ZDs/bin/x64/Debug/